### ISSUE TITLE
[Bug]: TestDouble.scriban generator crash on large interfaces (e.g. IAmazonS3) breaks build for whole compilation

### ISSUE THREAD

**Issue by ncipollina** [LayeredCraft/compono#142]
## What happened?

Upgrading `Compono`/`Compono.TestDoubles`/`Compono.XunitV3` from `0.8.0` to `1.3.0` (with `ComponoGeneratedTestDoubles=true`) breaks the build entirely when any composed interface is large (e.g. `Amazon.S3.IAmazonS3` — 171 declared members across 3 base interfaces). The `Compono.Generators` incremental generator throws inside its `TestDouble.scriban` template and produces zero output for the whole compilation:

```
CSC : warning CS8785: Generator 'ComponoIncrementalGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ScriptRuntimeException' with message 'TestDouble.scriban(373,24) : error : Exceeding number of iteration limit `1000` for loop statement.'.
TestDouble.scriban(373,24): error : Exceeding number of iteration limit `1000` for loop statement.
```

Because the generator crashes entirely (not just for the one large interface), **every** generated-double `Configure()`/`Verify()` extension in the compilation disappears — including for small, unrelated interfaces composed elsewhere in the same project. That surfaces as a wall of unrelated-looking compile errors, e.g.:

```
error CS1061: 'IResponseBuilder' does not contain a definition for 'Configure' ...
error CS1061: 'IHandlerInput' does not contain a definition for 'Configure' ...
error CS1061: 'ISkillMediator' does not contain a definition for 'Verify' ...
```

Expected: either the generator caps/streams whatever loop is hitting the 1000-iteration scriban limit so it can still emit a double for very large interfaces (or gracefully falls back per-interface, the way `CMP0020`/`CMP0021`/etc. already do for other unsupported shapes), or — at minimum — a single interface's generator failure shouldn't take down every other interface's generated double in the same compilation.

This worked fine on `Compono 0.8.0` with the exact same test code and the exact same `IAmazonS3` composition.

## Steps to reproduce

1. Create a test project with `Compono` 1.3.0, `Compono.TestDoubles` 1.3.0, `Compono.XunitV3` 1.3.0, and `<ComponoGeneratedTestDoubles>true</ComponoGeneratedTestDoubles>` set.
2. Reference `AWSSDK.S3` and compose `Amazon.S3.IAmazonS3` anywhere the generator's discovery walk reaches it, e.g.:
   ```csharp
   var composer = Composer.Create(builder => builder.UseGeneratedTestDoubles());
   var mockAmazonS3Client = composer.Create<IAmazonS3>();
   ```
   (also reproduces via an `IAmazonS3` `[Compose<TProfile>]` theory parameter)
3. Also compose at least one other, ordinary-sized interface in the same project (e.g. `IResponseBuilder`, `IHandlerInput`) using `Configure()`/`Verify()`.
4. Run `dotnet build`.

Actual: `CS8785` generator-failure warning + `TestDoubleNotConfiguredException`-unrelated `ScriptRuntimeException` in `TestDouble.scriban` at line 373, column 24 ("Exceeding number of iteration limit `1000` for loop statement"), and the *other* interfaces' `Configure()`/`Verify()` extensions are also missing, causing unrelated `CS1061`/`CS7036` errors elsewhere in the same project.

Expected: successful build, generated doubles for all eligible interfaces (or a documented `CMP00xx` diagnostic falling back gracefully for `IAmazonS3` specifically, without affecting other interfaces).

## Environment

- Compono 1.3.0, Compono.TestDoubles 1.3.0, Compono.XunitV3 1.3.0 (regression from 0.8.0, which worked)
- .NET 11.0 (preview SDK 11.0.100-rc.1.26425.128), macOS (Darwin 25.6.0, arm64)
- AWSSDK.S3 4.0.103.3 (`Amazon.S3.IAmazonS3`: 171 declared members, 3 base interfaces)
- xunit.v3.mtp-v2 4.0.1
